name: Preview Release Version

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  preview-release:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version to release
        id: pre-version
        uses: ./.github/actions/analyze-release

      - name: Comment on PR with bump info
        if: steps.pre-version.outputs.bump != ''
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ğŸš€ **PrÃ³ximo bump**: `${{ steps.pre-version.outputs.bump }}`
            ğŸš€ **Nueva versiÃ³n**: `${{ steps.pre-version.outputs.next_version }}`
            _(Basado en commits desde el tag `${{ steps.pre-version.outputs.last_tag }}`)_
          comment-tag: release-bump-preview

      - name: Comment on PR with bump info
        if: steps.pre-version.outputs.bump == ''
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ğŸš€ **PrÃ³ximo bump**: `âŒ No Release âŒ`
            _(Basado en commits desde el tag `${{ steps.pre-version.outputs.last_tag }}`)_
          comment-tag: release-bump-preview
